# Generated by Django 4.1.7 on 2023-04-11 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rooms',
            name='roomEquipment',
        ),
        migrations.AddField(
            model_name='rooms',
            name='roomEquipment',
            field=models.ManyToManyField(blank=True, null=True, to='api.roomequipment'),
        ),
    ]
