# Generated by Django 4.2 on 2023-04-12 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_rooms_roomequipment_rooms_roomequipment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rooms',
            name='roomEquipment',
            field=models.ManyToManyField(to='api.roomequipment'),
        ),
    ]
